import { expect, type Page, test } from "@playwright/test";

async function seedWorkflowStep(page: Page, step: number, projectName: string) {
  const seedResponse = await page.request.post("/api/dev/seed", {
    data: { step, projectName },
  });
  expect(seedResponse.ok()).toBe(true);
  const seed = (await seedResponse.json()) as {
    storageKey: string;
    snapshot: unknown;
  };

  await page.goto("/");
  await page.evaluate(
    ({ key, value }) => localStorage.setItem(key, JSON.stringify(value)),
    { key: seed.storageKey, value: seed.snapshot },
  );

  await page.goto(
    `/project/${projectName}/build?workflowChat=1&debugPanel=collapsed`,
  );

  await expect(page.getByTestId("workflow-chat-root")).toBeVisible();

  return seed;
}

test("WorkflowChat creates Step 1 artifact from form card responses", async ({
  page,
}) => {
  expect(process.env.USE_MOCK_ARTIFACTS).toBe("true");
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });

  const projectId = "workflow-chat-phase6-step1-form";
  const seed = await seedWorkflowStep(page, 1, projectId);

  await page
    .getByLabel("Do you have existing requirements?")
    .fill("No existing requirements yet");
  await page
    .getByLabel("What are you building?")
    .fill("A planning workflow assistant for software delivery teams.");
  await page.getByRole("button", { name: "Submit answer" }).click();

  await expect
    .poll(
      async () =>
        page.evaluate((key) => {
          const state = JSON.parse(localStorage.getItem(key) || "null");
          return {
            responses: state?.context?.step1Responses ?? {},
            advancedBeyondStep1: (state?.context?.currentStepNumber ?? 0) > 1,
            artifactContent: state?.context?.artifacts?.["1"]?.content ?? "",
          };
        }, seed.storageKey),
      { timeout: 30_000 },
    )
    .toMatchObject({
      responses: {
        existingRequirements: "No existing requirements yet",
        projectDescription:
          "A planning workflow assistant for software delivery teams.",
      },
      advancedBeyondStep1: true,
      artifactContent: expect.stringContaining(
        "Generated by mock artifact provider",
      ),
    });

  const createdArtifact = page
    .getByRole("button", {
      name: "Open artifact gap-analysis-worksheet.md from artifacts",
    })
    .first();
  await expect(createdArtifact).toBeEnabled();
  expect(consoleErrors).toEqual([]);
});

test("WorkflowChat creates Step 5 artifact from form card responses", async ({
  page,
}) => {
  expect(process.env.USE_MOCK_ARTIFACTS).toBe("true");
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });

  const projectId = "workflow-chat-phase6-step5-form";
  const seed = await seedWorkflowStep(page, 5, projectId);

  await page
    .getByLabel("What is the deployment strategy?")
    .fill("Deploy through the existing frontend pipeline.");
  await page
    .getByLabel("What is the tech stack?")
    .fill("React, XState, TanStack Start, TypeScript, and SQLite.");
  await page.getByRole("button", { name: "Submit answer" }).click();

  await expect
    .poll(
      async () =>
        page.evaluate((key) => {
          const state = JSON.parse(localStorage.getItem(key) || "null");
          return {
            responses: state?.context?.step5Responses ?? {},
            advancedBeyondStep5: (state?.context?.currentStepNumber ?? 0) > 5,
            artifactContent: state?.context?.artifacts?.["5"]?.content ?? "",
          };
        }, seed.storageKey),
      { timeout: 30_000 },
    )
    .toMatchObject({
      responses: {
        deploymentStrategy: "Deploy through the existing frontend pipeline.",
        techStack: "React, XState, TanStack Start, TypeScript, and SQLite.",
      },
      advancedBeyondStep5: true,
      artifactContent: expect.stringContaining(
        "Generated by mock artifact provider",
      ),
    });

  const createdArtifact = page
    .getByRole("button", {
      name: "Open artifact implementation-plan.yaml from artifacts",
    })
    .first();
  await expect(createdArtifact).toBeEnabled();
  expect(consoleErrors).toEqual([]);
});
