import { expect, type Page, test } from "@playwright/test";

type SeedResult = {
  storageKey: string;
  snapshot: unknown;
};

type AutomatedStepCase = {
  step: number;
  projectId: string;
  artifactName: string;
};

const automatedStepCases: AutomatedStepCase[] = [
  {
    step: 4,
    projectId: "workflow-chat-phase7-step4",
    artifactName: "style-anchors.md",
  },
  {
    step: 6,
    projectId: "workflow-chat-phase7-step6",
    artifactName: "plan-review.md",
  },
  {
    step: 8,
    projectId: "workflow-chat-phase7-step8",
    artifactName: "delivery-timeline.yaml",
  },
  {
    step: 9,
    projectId: "workflow-chat-phase7-step9",
    artifactName: "qa-test-plan.yaml",
  },
  {
    step: 10,
    projectId: "workflow-chat-phase7-step10",
    artifactName: "summaries.md",
  },
];

async function seedWorkflowStep(
  page: Page,
  step: number,
  projectName: string,
): Promise<SeedResult> {
  const seedResponse = await page.request.post("/api/dev/seed", {
    data: { step, projectName },
  });
  expect(seedResponse.ok()).toBe(true);

  const seed = (await seedResponse.json()) as SeedResult;
  await page.goto("/");
  await page.evaluate(
    ({ key, value }) => localStorage.setItem(key, JSON.stringify(value)),
    { key: seed.storageKey, value: seed.snapshot },
  );

  await page.goto(
    `/project/${projectName}/build?workflowChat=1&debugPanel=collapsed`,
  );
  await expect(page.getByTestId("workflow-chat-root")).toBeVisible();

  return seed;
}

for (const automatedStep of automatedStepCases) {
  test(`WorkflowChat creates automated Step ${automatedStep.step} artifact with mock provenance`, async ({
    page,
  }) => {
    expect(process.env.USE_MOCK_ARTIFACTS).toBe("true");
    const consoleErrors: string[] = [];
    page.on("console", (message) => {
      if (message.type() === "error") consoleErrors.push(message.text());
    });

    const seed = await seedWorkflowStep(
      page,
      automatedStep.step,
      automatedStep.projectId,
    );

    await expect
      .poll(
        async () =>
          page.evaluate(
            ({ key, step }) => {
              const state = JSON.parse(localStorage.getItem(key) || "null");
              return {
                artifactContent:
                  state?.context?.artifacts?.[String(step)]?.content ?? "",
              };
            },
            { key: seed.storageKey, step: automatedStep.step },
          ),
        { timeout: 30_000 },
      )
      .toMatchObject({
        artifactContent: expect.stringContaining(
          "Generated by mock artifact provider",
        ),
      });

    const createdArtifact = page
      .getByRole("button", {
        name: `Open artifact ${automatedStep.artifactName} from artifacts`,
      })
      .first();
    await expect(createdArtifact).toBeEnabled();

    await expect(
      page.getByText(
        `I've created the ${getAutomatedStepName(automatedStep.step)} artifact.`,
      ),
    ).toBeVisible();

    expect(consoleErrors).toEqual([]);
  });
}

function getAutomatedStepName(step: number): string {
  switch (step) {
    case 4:
      return "Style Anchors Collection";
    case 6:
      return "Implementation Plan Review";
    case 8:
      return "Delivery Timeline";
    case 9:
      return "QA Test Plan";
    case 10:
      return "Generate Summaries";
    default:
      throw new Error(`Unexpected automated step: ${step}`);
  }
}
