import { expect, test } from "@playwright/test";

const projectId = "workflow-chat-phase5-step3-mock";

const answers = [
  "State persistence should be handled first because workflow restore must be reliable.",
  "Use the existing React, XState, TanStack Start, and TypeScript stack.",
  "Persist workflow snapshots locally and through the planning_state database table.",
  "Generate artifacts through the configured mock artifact provider in local QA.",
  "Keep the WorkflowChat controller as the UI-to-machine adapter.",
  "Reuse existing interview answer persistence for Step 3 submissions.",
  "The main integration risk is losing context during artifact generation.",
  "Validate the result through DebugPanel state and localStorage snapshots.",
  "Step 3 should produce technical requirements from the submitted answers.",
  "After artifact creation the workflow should advance to Step 4.",
];

test("WorkflowChat creates Step 3 artifact with mock provenance", async ({
  page,
}) => {
  expect(process.env.USE_MOCK_ARTIFACTS).toBe("true");

  const seedResponse = await page.request.post("/api/dev/seed", {
    data: { step: 3, projectName: projectId },
  });
  expect(seedResponse.ok()).toBe(true);
  const seed = (await seedResponse.json()) as {
    storageKey: string;
    snapshot: unknown;
  };

  await page.goto("/");
  await page.evaluate(
    ({ key, value }) => localStorage.setItem(key, JSON.stringify(value)),
    { key: seed.storageKey, value: seed.snapshot },
  );

  await page.goto(
    `/project/${projectId}/build?workflowChat=1&debugPanel=collapsed`,
  );

  await expect(page.getByTestId("workflow-chat-root")).toBeVisible();
  await expect(page.getByTestId("chat-composer-input")).toBeEnabled();
  await expect(
    page.getByText("What technical risk should be handled first?"),
  ).toBeVisible();

  for (const answer of answers) {
    await page.getByTestId("chat-composer-input").fill(answer);
    await page.getByTestId("chat-composer-submit").click();
    await expect(page.getByText(answer, { exact: false })).toBeVisible();
  }

  await expect
    .poll(
      async () =>
        page.evaluate((key) => {
          const state = JSON.parse(localStorage.getItem(key) || "null");
          return {
            answerCount: state?.context?.step3Answers?.length ?? 0,
            advancedBeyondStep3: (state?.context?.currentStepNumber ?? 0) > 3,
            artifactContent: state?.context?.artifacts?.["3"]?.content ?? "",
          };
        }, seed.storageKey),
      { timeout: 30_000 },
    )
    .toMatchObject({
      answerCount: 10,
      advancedBeyondStep3: true,
      artifactContent: expect.stringContaining(
        "Generated by mock artifact provider",
      ),
    });

  await page.getByRole("button", { name: /Show Debug Panel/ }).click();
  await expect(page.getByText("Step 3 Answers: 10 items")).toBeVisible();
  await page.getByRole("button", { name: "Minimize" }).click();

  const createdArtifact = page
    .getByRole("button", {
      name: "Open artifact technical-requirements.yaml from artifacts",
    })
    .first();
  await expect(createdArtifact).toBeEnabled();
  await createdArtifact.click();

  await expect(
    page.getByRole("dialog", { name: /technical-requirements.yaml/i }),
  ).toBeVisible();
  await expect(
    page.getByText("Generated by mock artifact provider"),
  ).toBeVisible();
});
