import { expect, test } from "@playwright/test";

const projectId = "workflow-chat-phase4-mock";

const answers = [
  "Engineering leads need it first because they own delivery planning across teams.",
  "The main outcome is converting rough requirements into a delivery-ready implementation plan.",
  "Success means fewer missed dependencies, clearer milestones, and faster stakeholder sign-off.",
  "The primary constraint is keeping planning artifacts current without adding project-manager busywork.",
  "The workflow should support async collaboration between product, engineering, and delivery leads.",
  "The biggest risk is stale generated artifacts after requirements change.",
  "It should integrate with existing project documentation and issue planning workflows.",
  "Users need confidence that generated plans reflect their actual interview answers.",
  "The experience should make progress visible and make each next action obvious.",
  "The business value is repeatable planning quality across software delivery projects.",
];

test("WorkflowChat creates Step 2 artifact with mock provenance", async ({
  page,
}) => {
  expect(process.env.USE_MOCK_ARTIFACTS).toBe("true");

  const seedResponse = await page.request.post("/api/dev/seed", {
    data: { step: 2, projectName: projectId },
  });
  expect(seedResponse.ok()).toBe(true);
  const seed = (await seedResponse.json()) as {
    storageKey: string;
    snapshot: unknown;
  };

  await page.goto("/");
  await page.evaluate(
    ({ key, value }) => localStorage.setItem(key, JSON.stringify(value)),
    { key: seed.storageKey, value: seed.snapshot },
  );

  await page.goto(
    `/project/${projectId}/build?workflowChat=1&debugPanel=collapsed`,
  );

  await expect(page.getByTestId("workflow-chat-root")).toBeVisible();
  await expect(page.getByTestId("chat-composer-input")).toBeEnabled();
  await expect(
    page
      .getByRole("button", {
        name: "Artifact business-requirements.yaml is not available yet",
      })
      .first(),
  ).toBeDisabled();

  for (const answer of answers) {
    await page.getByTestId("chat-composer-input").fill(answer);
    await page.getByTestId("chat-composer-submit").click();
    await expect(page.getByText(answer, { exact: false })).toBeVisible();
  }

  await expect
    .poll(
      async () =>
        page.evaluate((key) => {
          const state = JSON.parse(localStorage.getItem(key) || "null");
          return {
            answerCount: state?.context?.step2Answers?.length ?? 0,
            artifactContent: state?.context?.artifacts?.["2"]?.content ?? "",
          };
        }, seed.storageKey),
      { timeout: 30_000 },
    )
    .toMatchObject({
      answerCount: 10,
      artifactContent: expect.stringContaining(
        "Generated by mock artifact provider",
      ),
    });

  const createdArtifact = page
    .getByRole("button", {
      name: "Open artifact business-requirements.yaml from artifacts",
    })
    .first();
  await expect(createdArtifact).toBeEnabled();
  await createdArtifact.click();

  await expect(
    page.getByRole("dialog", { name: /business-requirements.yaml/i }),
  ).toBeVisible();
  await expect(
    page.getByText("Generated by mock artifact provider"),
  ).toBeVisible();
});
