/**
 * XState v5 Type Definitions for Planning Machine
 *
 * All types are JSON-serializable for persistence support.
 */

/**
 * Step types determine the interaction pattern for each planning step
 */
export type StepType = "form" | "interview" | "automated" | "artifact-only";

/**
 * Artifact generated by AI for a given step
 */
export type Artifact = {
  type: "yaml" | "markdown";
  content: string;
  generatedAt: string;
};

/**
 * Form question configuration for form-type steps (Step 1, Step 5)
 */
export type FormQuestion = {
  id: string;
  label: string;
  type: "text" | "textarea" | "select";
  options?: string[];
};

/**
 * Interview answer captured during interview-type steps (Step 2, Step 3)
 */
export type InterviewAnswer = {
  question: string;
  value: string;
  timestamp: string;
};

/**
 * Map of step numbers to their generated artifacts
 */
export type StepArtifactMap = Record<number, Artifact | undefined>;

/**
 * Main planning machine context
 * All fields are JSON-serializable for localStorage persistence
 */
export type PlanningContext = {
  projectId: string;
  entryPath: "new-project" | "existing-project";
  startedAt: string;
  updatedAt: string;

  // Step 1: Gap Analysis (form)
  step1Responses: Record<string, string>;
  step1GapAnalysisNeeded: boolean | null; // null = not yet assessed
  step1GapAnalysisReasoning: string | null;

  // Step 2: Business Requirements (interview)
  step2Answers: InterviewAnswer[];
  step2CurrentQuestion: string | null;
  step2CurrentOptions: string[] | null;

  // Step 3: Technical Requirements (interview)
  step3Answers: InterviewAnswer[];
  step3CurrentQuestion: string | null;
  step3CurrentOptions: string[] | null;

  // Step 5: Implementation Planner (form)
  step5Responses: Record<string, string>;

  // Step 7: Architecture Decisions (artifact-only)
  step7Edits: string | null;

  // Accumulated artifacts
  artifacts: StepArtifactMap;

  // Navigation tracking
  completedSteps: number[]; // Array of step numbers (1-10) that are complete
  currentStepNumber: number; // Current step number (1-10)

  // Error state
  error: string | null;
};

/**
 * Events that can be sent to the planning machine
 */
export type PlanningEvent =
  | { type: "START_PLANNING" }
  | {
      type: "SUBMIT_FORM";
      stepNumber: number;
      responses: Record<string, string>;
    }
  | {
      type: "SUBMIT_ANSWER";
      stepNumber: number;
      question: string;
      answer: string;
    }
  | { type: "STEP_SIGNAL_COMPLETE"; stepNumber: number }
  | { type: "EDIT_ARTIFACT"; stepNumber: number; content: string }
  | { type: "APPROVE_ARTIFACT"; stepNumber: number }
  | { type: "RESUME_AUTOMATED_STEP"; stepNumber: number }
  | { type: "RETRY"; stepNumber: number }
  | { type: "RESET_PROJECT" }
  | { type: "NEXT" }
  | { type: "BACK" }
  | {
      type: "RESTORE_SNAPSHOT";
      snapshot: {
        context: PlanningContext;
        // biome-ignore lint/suspicious/noExplicitAny: XState snapshot value can be any state value
        value?: any;
      };
    };

/**
 * Input required to initialize the planning machine
 */
export type PlanningInput = {
  projectId: string;
  entryPath: "new-project" | "existing-project";
};
