import { getStepName } from "../planning/step-config";

export const MOCK_ARTIFACT_PROVENANCE = "Generated by mock artifact provider";

export function shouldUseMockArtifacts(): boolean {
  return process.env.USE_MOCK_ARTIFACTS === "true";
}

export function assertMockArtifactsAllowed(): void {
  if (shouldUseMockArtifacts() && process.env.NODE_ENV === "production") {
    throw new Error(
      "USE_MOCK_ARTIFACTS=true is not allowed when NODE_ENV=production",
    );
  }
}

export function generateMockArtifactContent(
  stepNumber: number,
  answers: string[],
): string {
  const stepName = getStepName(stepNumber);
  const answerPreview = answers
    .slice(0, 3)
    .map((answer, index) => `  - ${index + 1}: ${JSON.stringify(answer)}`)
    .join("\n");

  return [
    `# ${stepName}`,
    "",
    `provenance: "${MOCK_ARTIFACT_PROVENANCE}"`,
    "provider: mock",
    `step_number: ${stepNumber}`,
    `answer_count: ${answers.length}`,
    "answer_preview:",
    answerPreview || "  []",
    "",
    "summary: Deterministic mock artifact for local and CI workflow validation.",
  ].join("\n");
}
