#!/usr/bin/env node

const mockArtifactsEnabled = process.env.USE_MOCK_ARTIFACTS === "true";
const production = process.env.NODE_ENV === "production";

if (mockArtifactsEnabled && production) {
  console.error(
    JSON.stringify(
      {
        ok: false,
        check: "ai",
        code: "MOCK_ARTIFACTS_PRODUCTION_FORBIDDEN",
        message:
          "USE_MOCK_ARTIFACTS=true is not allowed when NODE_ENV=production.",
      },
      null,
      2,
    ),
  );
  process.exit(1);
}

if (mockArtifactsEnabled) {
  console.log(
    JSON.stringify(
      {
        ok: true,
        check: "ai",
        mode: "mock-artifacts",
        provenance: "Generated by mock artifact provider",
      },
      null,
      2,
    ),
  );
  process.exit(0);
}

await import("./check-bedrock.mjs");
