import { useState } from 'react'
import { DocList, type DocGroup } from './DocList'
import { CodePreview } from './CodePreview'

const SAMPLE_CODE = `# business-requirements.yaml
# generated by sherpy · stage 02 · v12
# last updated: just now

project:     sherpy-web
run_id:      run-04
stage:       business-requirements
status:      in-progress
version:     12

stakeholders:
  primary:   solo-engineers
  secondary: tech-leads
  decider:   @validkeys

outcomes:
  - id: O1
    title: "Drive Sherpy skills via UI"
    measure: "95% of CLI flows reachable"
  - id: O2
    title: "Preserve gap discipline"
    measure: "0 promotions w/ open gaps"

constraints:
  runtime:  browser-only
  offline:  true
  auth:     ⚠ unresolved — gap #1
  storage:  ⚠ unresolved — gap #2

acceptance:
  - "User completes 5-stage flow in < 90m"
  - "All artifacts diffable as plain text"
▌`

const SAMPLE_GROUPS: DocGroup[] = [
  {
    label: 'Stage 02 · Business',
    stageColor: 'var(--bot-2)',
    docs: [
      {
        name: 'business-requirements.yaml',
        streaming: true,
        version: 'v12',
        time: 'just now',
        size: '17.4 KB',
        stageColor: 'var(--bot-2)',
      },
      {
        name: 'stakeholder-map.md',
        version: 'v3',
        time: '4m ago',
        size: '6.1 KB',
        stageColor: 'var(--bot-2)',
      },
    ],
  },
  {
    label: 'Stage 01 · Gap analysis',
    stageColor: 'var(--bot-1)',
    docs: [
      {
        name: 'gap-analysis.yaml',
        version: 'v6',
        time: 'signed off',
        size: '12.8 KB',
        stageColor: 'var(--bot-1)',
      },
      {
        name: 'research-notes.md',
        version: 'v2',
        time: 'signed off',
        size: '9.4 KB',
        stageColor: 'var(--bot-1)',
      },
      {
        name: 'verification.jsonl',
        streaming: true,
        version: 'v4',
        time: 'streaming',
        size: '3.2 KB',
        stageColor: 'var(--bot-1)',
      },
    ],
  },
  {
    label: 'Workspace',
    stageColor: 'var(--neutral-4)',
    docs: [
      {
        name: 'project.yaml',
        version: 'v1',
        time: '1h ago',
        size: '1.1 KB',
        stageColor: 'var(--neutral-4)',
      },
      {
        name: 'README.md',
        version: 'v1',
        time: '1h ago',
        size: '2.4 KB',
        stageColor: 'var(--neutral-4)',
      },
    ],
  },
]

function findDoc(name: string) {
  for (const group of SAMPLE_GROUPS) {
    const doc = group.docs.find((d) => d.name === name)
    if (doc) return { doc, group }
  }
  return null
}

export function ReviewView() {
  const [activeDoc, setActiveDoc] = useState('business-requirements.yaml')

  const found = findDoc(activeDoc)
  const doc = found?.doc
  const group = found?.group

  return (
    <div className="grid grid-cols-[320px_1fr] flex-1 min-h-0 border-t border-border-1 mt-6">
      <DocList
        groups={SAMPLE_GROUPS}
        activeDoc={activeDoc}
        onDocClick={setActiveDoc}
      />
      {doc && group ? (
        <CodePreview
          filePath={`requirements / ${doc.name}`}
          fileName={doc.name}
          streaming={doc.streaming}
          stageName={group.label}
          stageColor={group.stageColor}
          version={doc.version}
          lastEdited={doc.time}
          fileSize={doc.size}
          sha="8a2f9c1"
          gapCount={doc.name === 'business-requirements.yaml' ? 2 : 0}
          diffLabel={doc.name === 'business-requirements.yaml' ? 'v11→v12' : undefined}
          sourceCode={doc.name === 'business-requirements.yaml' ? SAMPLE_CODE : `# ${doc.name}\n# no content`}
        />
      ) : (
        <div className="flex items-center justify-center text-fg-4 font-mono text-[12px]">
          select a document
        </div>
      )}
    </div>
  )
}
