/**
 * Domain layer: Pure command functions for planning step state (write-side).
 *
 * These functions return new state without mutating the input.
 * All commands follow immutable patterns: oldState → newState.
 *
 * @module features/planning/domain/step-commands
 */

import type { ProjectStepState, StepAnswer } from "../types";
import type { StepNumber } from "./types";

/**
 * Submit an answer for a specific step's question.
 *
 * Business rule: Answers are appended to the step's answers array.
 * Multiple answers per step are supported for multi-turn interviews.
 *
 * @param state - Current project state
 * @param stepNumber - Step number (1-10)
 * @param question - The question being answered
 * @param answer - The user's answer
 * @returns New state with answer added (immutable)
 * @throws Error if step not found
 */
export function submitStepAnswer(
  state: ProjectStepState,
  stepNumber: StepNumber,
  question: string,
  answer: string,
): ProjectStepState {
  const step = state.steps.find((s) => s.stepNumber === stepNumber);
  if (!step) {
    throw new Error(`Step ${stepNumber} not found`);
  }

  const newAnswer: StepAnswer = {
    question,
    value: answer,
    submittedAt: new Date().toISOString(),
  };

  return {
    ...state,
    steps: state.steps.map((s) =>
      s.stepNumber === stepNumber
        ? {
            ...s,
            answers: [...(s.answers || []), newAnswer],
          }
        : s,
    ),
  };
}

/**
 * Mark a step as complete and advance workflow to next step.
 *
 * Business rules:
 * - Completing step 1-9: marks step complete, advances currentStep to next
 * - Completing step 10: marks step complete, currentStep stays at 10 (workflow done)
 * - Next step status changes from "pending" to "now"
 *
 * @param state - Current project state
 * @param stepNumber - Step number to complete (1-10)
 * @returns New state with step completed (immutable)
 */
export function completeStep(
  state: ProjectStepState,
  stepNumber: StepNumber,
): ProjectStepState {
  if (stepNumber >= 10) {
    // Last step completed - workflow done
    return {
      ...state,
      currentStep: 10,
      steps: state.steps.map((s) =>
        s.stepNumber === stepNumber ? { ...s, status: "complete" } : s,
      ),
    };
  }

  const nextStep = (stepNumber + 1) as StepNumber;

  return {
    ...state,
    currentStep: nextStep,
    steps: state.steps.map((s) =>
      s.stepNumber === stepNumber
        ? { ...s, status: "complete" }
        : s.stepNumber === nextStep
          ? { ...s, status: "now" }
          : s,
    ),
  };
}

/**
 * Set the generated artifact content for a step.
 *
 * Artifacts are YAML or markdown documents generated by AI during the workflow.
 * Setting an artifact overwrites any existing artifact for that step.
 *
 * @param state - Current project state
 * @param stepNumber - Step number (1-10)
 * @param artifact - Generated artifact content (YAML or markdown)
 * @returns New state with artifact set (immutable)
 */
export function setStepArtifact(
  state: ProjectStepState,
  stepNumber: StepNumber,
  artifact: string,
): ProjectStepState {
  return {
    ...state,
    steps: state.steps.map((s) =>
      s.stepNumber === stepNumber ? { ...s, artifact } : s,
    ),
  };
}

/**
 * Skip a step and advance workflow to next step.
 *
 * Business rules:
 * - Step is marked as "skipped"
 * - Workflow advances to next step (currentStep incremented)
 * - Next step status changes from "pending" to "now"
 *
 * Note: Some steps may be skippable based on workflow business rules
 * (e.g., Gap Analysis can be skipped if starting from scratch).
 *
 * @param state - Current project state
 * @param stepNumber - Step number to skip (1-10)
 * @returns New state with step skipped (immutable)
 */
export function skipStep(
  state: ProjectStepState,
  stepNumber: StepNumber,
): ProjectStepState {
  const nextStep = (stepNumber + 1) as StepNumber;

  return {
    ...state,
    currentStep: nextStep,
    steps: state.steps.map((s) =>
      s.stepNumber === stepNumber
        ? { ...s, status: "skipped" }
        : s.stepNumber === nextStep
          ? { ...s, status: "now" }
          : s,
    ),
  };
}

/**
 * Create an interview answer object with timestamp.
 *
 * Pure factory function for creating interview answer records.
 * Used by XState machine to construct answers in a consistent format.
 *
 * @param question - The question being answered
 * @param answer - The user's answer
 * @returns Interview answer object with timestamp
 */
export function createInterviewAnswer(
  question: string,
  answer: string,
): { question: string; value: string; timestamp: string } {
  return {
    question,
    value: answer,
    timestamp: new Date().toISOString(),
  };
}
